config/routes.rb
Rails.application.routes.draw do
  root 'students#index'

  resources :students, only: [:index, :new, :create]
  resources :enrollments, only: [:index, :new, :create]
  resources :syncs, only: [:index, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :enrollments
  has_many :students, through: :enrollments

  validates :name, presence: true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :student
  belongs_to :course

  validates :enrolled_at, presence: true
  validates :student_id, uniqueness: { scope: :course_id,
    message: 'não pode estar matriculado mais de uma vez no mesmo curso' }
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :enrollments
  has_many :courses, through: :enrollments

  validates :name, :email, :phone, :street, :street_number, :neighborhood, :city, :state,
    :postal_code, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  def index
    @enrollments = Enrollment.includes(:student, :course).all
  end

  def new
    @enrollment = Enrollment.new
  end

  def create
    @enrollment = Enrollment.new(enrollment_params)

    if @enrollment.save
      redirect_to enrollments_path, notice: 'Nova matrícula efetuada com sucesso.'
    else
      render :new
    end
  end

  private

  def enrollment_params
    params.require(:enrollment).permit(:student_id, :course_id, :enrolled_at)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to students_path, notice: 'Novo aluno criado com sucesso.'
    else
      render :new
    end
  end

  private

  def student_params
    params.require(:student).permit(:name, :email, :phone, :street, :street_number,
      :neighborhood, :city, :state, :postal_code)
  end
end

app/controllers/syncs_controller.rb
require 'net/http'

class SyncsController < ApplicationController
  def index
  end

  # Simula um POST para uma API fictícia do MEC. Em uma aplicação real,
  # o ideal seria que esse tipo de requisição a serviço externo acontecesse
  # em background, já que é uma operação sujeita a falhas e mais lenta
  # (e queremos que nossa aplicação seja capaz de servir requisições o mais rápido
  # possível, já que assim conseguimos atender mais requisições por segundo com
  # hardware menos poderoso).
  def create
    url = URI('http://www.mocky.io/v2/59bf19a326000016035261e6')
    req = Net::HTTP::Post.new(url)
    req.body = { students: Student.all }.to_json
    req['Content-Type'] = 'application/json'

    response = Net::HTTP.start(url.hostname, url.port, use_ssl: false) do |http|
      http.request(req)
    end

    if response.code == '201'
      redirect_to syncs_path, notice: 'Dados sincronizados com sucesso.'
    else
      redirect_to syncs_path, alert: 'Houve um erro ao tentar sincronizar os dados.' \
        ' Por favor, tente novamente mais tarde.'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_flash_msgs
    msgs = ''
    msgs += show_msg_type('notice', 'alert-success')
    msgs += show_msg_type('alert', 'alert-danger')
    msgs.html_safe
  end

  def errors_of(object, attrs_to_ignore = [], custom_title = 'Não foi possível salvar devido aos seguintes erros:')
    attrs_to_ignore.each { |attr_to_ignore| object.errors.delete(attr_to_ignore) }

    errors_markup = ''
    if object.errors.any?
      errors_markup += '<div class="default-margin-b text-danger">'
      errors_markup += "<p><b>#{custom_title}</b></p>"
      errors_markup += '<ul>'
      object.errors.full_messages.each do |msg|
        errors_markup += "<li>#{msg}</li>"
      end
      errors_markup += '</ul></div>'
    end

    errors_markup.html_safe
  end

  private

  def show_msg_type(type, css_classes)
    css_classes ||= ''
    css_classes += ' alert'
    msg = ''
    unless flash[type].blank?
      msg += "<div class='#{css_classes}' role='alert'>"
      msg += "<p>#{flash[type]}</p>"
      msg += "</div>"
    end
    msg
  end
end

app/views/enrollments/index.html.slim
.row
  .col-md-10.col-md-offset-1
    h1.default-margin-b Matrículas
    - if @enrollments.any?
      table.table
        thead
          tr
            th Data da matrícula
            th Aluno
            th Curso
        tbody
          - @enrollments.each do |enrollment|
            tr
              td
                = enrollment.enrolled_at.strftime('%d/%m/%Y')
              td
                = enrollment.student.name
              td
                = enrollment.course.name
    - else
      p Ainda não há matrículas efetuadas.
    .default-margin-t.default-margin-b
      = link_to('Nova matrícula', new_enrollment_path, class: 'btn btn-default')

app/views/enrollments/new.html.slim
.row
  .col-md-10.col-md-offset-1
    h1.default-margin-b Nova matrícula

    = errors_of @enrollment
    = form_for @enrollment, html: { role: 'form', novalidate: 'novalidate' } do |f|
      .form-group
        = f.label :student_id
        = f.select :student_id,
          Student.all.map { |p| [p.name, p.id] },
          { include_blank: 'Selecione um aluno' },
          class: 'form-control'
      .form-group
        = f.label :course_id
        = f.select :course_id,
          Course.all.map { |c| [c.name, c.id] },
          { include_blank: 'Selecione um curso' },
          class: 'form-control'
      .form-group
        = f.label :enrolled_at, style: 'display: block;'
        = f.date_select :enrolled_at,
          {},
          class: 'form-control',
          style: 'display: inline-block; width: 150px;'

      = f.submit 'Salvar', class: 'btn btn-success'

    .default-margin-t.default-margin-b
      = link_to('Ir para a listagem de matrículas', enrollments_path)

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-default role='navigation'
  .navbar-header
    button.navbar-toggle type='button' data-toggle='collapse' data-target='#navbar_collapse_1'
      span.sr-only
        | Expandir ou contrair
      span.icon-bar
      span.icon-bar
      span.icon-bar
  #navbar_collapse_1.collapse.navbar-collapse
    ul.nav.navbar-nav
      li.dropdown
        a.dropdown-toggle href='#' data-toggle='dropdown'
          | Alunos
          b< class='caret'
        ul.dropdown-menu
          li
            = link_to 'Listagem', students_path
          li
            = link_to 'Novo', new_student_path
          li
            = link_to 'Sincronizar dados com o MEC', syncs_path, method: :post
      li.dropdown
        a.dropdown-toggle href='#' data-toggle='dropdown'
          | Matrículas
          b< class='caret'
        ul.dropdown-menu
          li
            = link_to 'Listagem', enrollments_path
          li
            = link_to 'Nova', new_enrollment_path

app/views/layouts/application.html.slim
doctype html
html lang='pt-BR'
  head
    title
      | Sistema Acadêmico - Anna Carolina Alvarenga

    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'

  body
    = render 'layouts/navbar'

    .container
      .row
        .col-md-10.col-md-offset-1
          = show_flash_msgs

      == yield

app/views/students/index.html.slim
.row
  .col-md-10.col-md-offset-1
    h1.default-margin-b Alunos
    - if @students.any?
      table.table
        thead
          tr
            th Nome
            th Dados pessoais
            th Endereço
        tbody
          - @students.each do |student|
            tr
              td
                = student.name
              td
                | Email: #{student.email}<br />
                | Telefone: #{student.phone}
              td
                | #{student.street}, #{student.street_number}. #{student.neighborhood}.<br />
                | #{student.city} - #{student.state}.<br />
                | CEP: #{student.postal_code}
    - else
      p Ainda não há alunos cadastrados.
    .default-margin-t.default-margin-b
      = link_to('Novo aluno', new_student_path, class: 'btn btn-default small-margin-r')
      = link_to('Sincronizar dados com o MEC', syncs_path, class: 'btn btn-default', method: :post)

app/views/students/new.html.slim
.row
  .col-md-10.col-md-offset-1
    h1.default-margin-b Novo aluno

    = errors_of @student
    = form_for @student, html: { role: 'form', novalidate: 'novalidate' } do |f|
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'
      .form-group
        = f.label :email
        = f.email_field :email, class: 'form-control'
      .form-group
        = f.label :phone
        = f.phone_field :phone, class: 'form-control'
      .form-group
        = f.label :street
        = f.text_field :street, class: 'form-control'
      .form-group
        = f.label :street_number
        = f.number_field :street_number, class: 'form-control'
      .form-group
        = f.label :neighborhood
        = f.text_field :neighborhood, class: 'form-control'
      .form-group
        = f.label :city
        = f.text_field :city, class: 'form-control'
      .form-group
        = f.label :state
        = f.text_field :state, class: 'form-control'
      .form-group
        = f.label :postal_code
        = f.text_field :postal_code, class: 'form-control'

      = f.submit 'Salvar', class: 'btn btn-success'

    .default-margin-t.default-margin-b
      = link_to('Ir para a listagem de alunos', students_path)

app/views/syncs/index.html.slim
.row
  .col-md-10.col-md-offset-1
    h1.default-margin-b Sincronização com o MEC
    p
      | Use o botão abaixo para enviar todos os alunos cadastrados
      |  para os sistemas do Ministério da Educação e Cultura.
    .default-margin-t.default-margin-b
      = link_to('Sincronizar dados com o MEC', syncs_path, class: 'btn btn-default', method: :post)